<?php

namespace AppBundle\Repository;

/**
 * CabReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabReporteRepository extends \Doctrine\ORM\EntityRepository
{
}
