<?php

namespace AppBundle\Repository;

/**
 * DetReporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetReporteRepository extends \Doctrine\ORM\EntityRepository
{
}
